// Plantillas de Matriz de Riesgos y Controles por industria — Cabrera & Consultores
// Cada fila = par riesgo–control (mismo formato que la importación desde Excel).
// Campos: area, subproceso, riesgo_codigo, riesgo, descripcion, categoria, probabilidad, impacto,
//         error_potencial, cuenta, aseveraciones, control_codigo, control, objetivo_control,
//         tipo, naturaleza, frecuencia, clave

const f = (area, subproceso, rc, riesgo, descripcion, categoria, p, i, cc, control, tipo, naturaleza, frecuencia, clave, extra = {}) =>
  ({ area, subproceso, riesgo_codigo: rc, riesgo, descripcion, categoria, probabilidad: p, impacto: i, control_codigo: cc, control, tipo, naturaleza, frecuencia, clave, ...extra });

const SOFOM = [
  // Originación de crédito
  f('Crédito', 'Originación', 'CRE-R01', 'Otorgamiento de crédito sin validar capacidad de pago',
    'Falta de análisis de ingresos y endeudamiento provoca colocación a acreditados insolventes, incrementando la cartera vencida.',
    'Proceso', 4, 5, 'CRE-C01', 'Análisis de capacidad de pago con consulta a Sociedad de Información Crediticia y validación de ingresos', 'preventivo', 'manual', 'continua', true,
    { error_potencial: 'Reservas preventivas insuficientes', cuenta: 'Cartera de crédito / Estimación preventiva', aseveraciones: 'Valuación' }),
  f('Crédito', 'Originación', 'CRE-R01', 'Otorgamiento de crédito sin validar capacidad de pago', '', 'Proceso', 4, 5,
    'CRE-C02', 'Autorización por Comité de Crédito conforme a facultades y montos aprobados por el Consejo', 'preventivo', 'manual', 'semanal', true),
  f('Crédito', 'Originación', 'CRE-R02', 'Expediente de crédito incompleto o con documentación apócrifa',
    'Integración deficiente del expediente impide la cobranza judicial y facilita fraudes de identidad.',
    'Fraude externo', 3, 4, 'CRE-C03', 'Checklist de integración de expediente y validación biométrica/INE ante el padrón del INE', 'preventivo', 'manual', 'continua', true,
    { aseveraciones: 'Existencia u ocurrencia, Derechos y obligaciones' }),
  f('Crédito', 'Administración de cartera', 'CRE-R03', 'Calificación de cartera y reservas preventivas incorrectas',
    'Errores en la metodología o en los insumos de calificación generan estimaciones preventivas subvaluadas.',
    'Contable', 3, 5, 'CRE-C04', 'Recálculo mensual independiente de la calificación de cartera y conciliación contra contabilidad', 'detectivo', 'manual', 'mensual', true,
    { error_potencial: 'Subestimación de reservas', cuenta: 'Estimación preventiva para riesgos crediticios', aseveraciones: 'Valuación, Exactitud' }),
  // Cobranza
  f('Cobranza', 'Gestión de cobranza', 'COB-R01', 'Prácticas de cobranza indebidas o fuera de normativa',
    'Gestores o despachos externos contactan a deudores fuera de horario o con trato inadecuado, generando quejas y sanciones.',
    'Cumplimiento con leyes', 3, 4, 'COB-C01', 'Monitoreo de grabaciones y bitácora de gestiones de despachos externos conforme a disposiciones de CONDUSEF', 'detectivo', 'manual', 'mensual', true),
  f('Cobranza', 'Aplicación de pagos', 'COB-R02', 'Pagos de clientes no aplicados o aplicados a cuenta incorrecta',
    'Errores en la aplicación de depósitos generan saldos incorrectos y cobros indebidos.',
    'Proceso', 3, 3, 'COB-C02', 'Conciliación diaria automatizada de depósitos bancarios contra aplicación en sistema de cartera', 'detectivo', 'automatico', 'diaria', true,
    { cuenta: 'Cartera de crédito / Bancos', aseveraciones: 'Integridad, Exactitud' }),
  // PLD
  f('Prevención de Lavado de Dinero', 'Conocimiento del cliente', 'PLD-R01', 'Incumplimiento de identificación y conocimiento del cliente (KYC)',
    'Alta de clientes sin identificación completa ni grado de riesgo expone a sanciones de la CNBV y uso de la entidad para operaciones ilícitas.',
    'Crimen Financiero', 3, 5, 'PLD-C01', 'Validación de expediente KYC y asignación de grado de riesgo antes de liberar la operación', 'preventivo', 'manual', 'continua', true),
  f('Prevención de Lavado de Dinero', 'Monitoreo', 'PLD-R02', 'Omisión en la detección y reporte de operaciones inusuales',
    'Falta de alertas o análisis tardío impide reportar en tiempo a la UIF.',
    'Crimen Financiero', 3, 5, 'PLD-C02', 'Sistema de alertas automatizado y dictamen del Oficial de Cumplimiento con envío de reportes regulatorios en plazo', 'detectivo', 'automatico', 'diaria', true),
  f('Prevención de Lavado de Dinero', 'Monitoreo', 'PLD-R03', 'Operaciones con personas en listas bloqueadas o PEP sin escalamiento',
    'No se consultan listas o no se escalan coincidencias, lo que deriva en operaciones prohibidas.',
    'Crimen Financiero', 2, 5, 'PLD-C03', 'Consulta automática contra Lista de Personas Bloqueadas y listas internacionales en alta y en cada operación', 'preventivo', 'automatico', 'continua', true),
  // Tesorería y fondeo
  f('Tesorería', 'Dispersión de recursos', 'TES-R01', 'Dispersión de créditos a cuentas no autorizadas',
    'Alteración de cuentas destino o falta de segregación permite desviar recursos.',
    'Fraude interno', 3, 5, 'TES-C01', 'Doble firma electrónica en banca y validación de cuenta CLABE contra expediente del acreditado', 'preventivo', 'manual', 'continua', true,
    { cuenta: 'Bancos', aseveraciones: 'Existencia u ocurrencia' }),
  f('Tesorería', 'Fondeo y liquidez', 'TES-R02', 'Riesgo de liquidez por descalce entre fondeo y colocación',
    'Falta de proyección de flujos provoca incapacidad para fondear la colocación o cumplir con acreedores.',
    'Gobierno', 3, 4, 'TES-C02', 'Proyección semanal de flujos y seguimiento de límites de liquidez reportado al Comité de Riesgos', 'detectivo', 'manual', 'semanal', false),
  f('Tesorería', 'Conciliaciones', 'TES-R03', 'Partidas en conciliación bancaria sin aclarar',
    'Diferencias antiguas ocultan errores o desvíos de recursos.',
    'Contable', 3, 3, 'TES-C03', 'Conciliación bancaria mensual revisada y firmada por la Contraloría, con antigüedad de partidas', 'detectivo', 'manual', 'mensual', true,
    { cuenta: 'Bancos', aseveraciones: 'Existencia u ocurrencia, Integridad' }),
  // TI y ciberseguridad
  f('Tecnología', 'Accesos', 'TI-R01', 'Accesos no autorizados al sistema de cartera',
    'Usuarios genéricos, cuentas de bajas activas o privilegios excesivos permiten modificar saldos o datos de clientes.',
    'Información y Ciberseguridad', 3, 5, 'TI-C01', 'Revisión trimestral de usuarios y perfiles, y baja inmediata al terminar la relación laboral', 'detectivo', 'manual', 'trimestral', true),
  f('Tecnología', 'Continuidad', 'TI-R02', 'Pérdida de información por falla o ataque de ransomware',
    'Ausencia de respaldos probados interrumpe la operación y compromete datos de clientes.',
    'Continuidad de Negocio', 2, 5, 'TI-C02', 'Respaldos diarios cifrados fuera de sitio con prueba de restauración trimestral', 'correctivo', 'automatico', 'diaria', true),
  // Cumplimiento regulatorio
  f('Cumplimiento', 'Reportes regulatorios', 'CUM-R01', 'Envío extemporáneo o erróneo de reportes regulatorios',
    'Incumplimiento de plazos ante CNBV, CONDUSEF o SIC genera multas y observaciones.',
    'Cumplimiento con leyes', 3, 4, 'CUM-C01', 'Calendario regulatorio con responsables, revisión previa y acuse de envío', 'preventivo', 'manual', 'mensual', true),
  f('Cumplimiento', 'Atención a usuarios', 'CUM-R02', 'Quejas de usuarios no atendidas en plazo (UNE)',
    'Falta de atención oportuna a reclamaciones deriva en sanciones de CONDUSEF y daño reputacional.',
    'Prácticas de negocio', 3, 3, 'CUM-C02', 'Registro y seguimiento de reclamaciones de la UNE con semáforo de plazos', 'detectivo', 'manual', 'semanal', false),
];

const HOSPITAL = [
  f('Admisión y Caja', 'Admisión', 'ADM-R01', 'Ingreso de pacientes sin garantía de pago o autorización de aseguradora',
    'Pacientes particulares o asegurados ingresan sin depósito o carta de autorización, generando cuentas incobrables.',
    'Proceso', 4, 4, 'ADM-C01', 'Validación de garantía (depósito o carta de autorización de aseguradora) previa al ingreso programado', 'preventivo', 'manual', 'continua', true,
    { cuenta: 'Cuentas por cobrar', aseveraciones: 'Valuación' }),
  f('Admisión y Caja', 'Caja', 'ADM-R02', 'Faltantes o malversación de efectivo en caja',
    'Manejo de efectivo sin arqueos ni segregación permite sustracciones.',
    'Fraude interno', 3, 3, 'ADM-C02', 'Arqueo sorpresivo de caja y corte diario conciliado contra el sistema', 'detectivo', 'manual', 'diaria', true,
    { cuenta: 'Caja y bancos', aseveraciones: 'Existencia u ocurrencia' }),
  f('Facturación y Cobranza', 'Cuenta del paciente', 'FAC-R01', 'Cargos no registrados en la cuenta del paciente',
    'Insumos y servicios consumidos no se cargan, provocando pérdida de ingresos.',
    'Proceso', 4, 4, 'FAC-C01', 'Conciliación de consumos de farmacia, quirófano y estudios contra la cuenta antes del alta', 'detectivo', 'manual', 'continua', true,
    { cuenta: 'Ingresos por servicios', aseveraciones: 'Integridad' }),
  f('Facturación y Cobranza', 'Aseguradoras', 'FAC-R02', 'Rechazos y glosas de aseguradoras por documentación incompleta',
    'Expedientes incompletos o fuera de tabulador generan rechazos y cartera envejecida.',
    'Proceso', 4, 4, 'FAC-C02', 'Revisión previa de documentación y tabuladores por convenio antes del envío a la aseguradora', 'preventivo', 'manual', 'continua', true),
  f('Farmacia', 'Inventario', 'FAR-R01', 'Merma, caducidad o sustracción de medicamentos',
    'Control deficiente de inventarios genera pérdidas y riesgo sanitario.',
    'Fraude interno', 4, 4, 'FAR-C01', 'Inventarios cíclicos con conteo ciego y control de caducidades (PEPS)', 'detectivo', 'manual', 'mensual', true,
    { cuenta: 'Inventario de medicamentos', aseveraciones: 'Existencia u ocurrencia, Valuación' }),
  f('Farmacia', 'Medicamentos controlados', 'FAR-R02', 'Manejo indebido de medicamentos controlados (estupefacientes y psicotrópicos)',
    'Falta de libro de control o recetas válidas expone a sanciones de COFEPRIS y a desvío de sustancias.',
    'Cumplimiento con leyes', 3, 5, 'FAR-C02', 'Libro de control autorizado, receta especial y doble verificación del responsable sanitario', 'preventivo', 'manual', 'continua', true),
  f('Quirófano', 'Programación', 'QUI-R01', 'Cirugía en paciente, sitio o procedimiento equivocado',
    'Fallas en la verificación preoperatoria provocan eventos adversos graves.',
    'Seguridad de Gente y Activos', 2, 5, 'QUI-C01', 'Lista de verificación de cirugía segura (OMS) firmada por el equipo quirúrgico', 'preventivo', 'manual', 'continua', true),
  f('Quirófano', 'Consumos', 'QUI-R02', 'Material de osteosíntesis o consigna no cobrado o no conciliado con proveedor',
    'Material en consignación usado y no reportado genera pérdidas y conflictos con proveedores.',
    'Proceso', 3, 4, 'QUI-C02', 'Hoja de consumo quirúrgico firmada y conciliación semanal de consigna con proveedores', 'detectivo', 'manual', 'semanal', true),
  f('Expediente Clínico', 'Integración', 'EXP-R01', 'Expediente clínico incompleto (NOM-004-SSA3)',
    'Notas médicas o consentimientos faltantes exponen a responsabilidad legal y rechazos de aseguradoras.',
    'Legal', 3, 4, 'EXP-C01', 'Auditoría mensual de una muestra de expedientes contra la NOM-004 con retroalimentación al médico', 'detectivo', 'manual', 'mensual', true),
  f('Expediente Clínico', 'Privacidad', 'EXP-R02', 'Divulgación no autorizada de datos personales sensibles de pacientes',
    'Accesos sin control al expediente vulneran la LFPDPPP.',
    'Información y Ciberseguridad', 2, 5, 'EXP-C02', 'Perfiles de acceso por rol al sistema hospitalario y bitácora de consultas al expediente', 'preventivo', 'automatico', 'continua', true),
  f('Compras', 'Adquisiciones', 'COM-R01', 'Compras sin cotizaciones o a proveedores relacionados',
    'Adjudicaciones directas sin competencia generan sobreprecios y conflictos de interés.',
    'Fraude interno', 3, 4, 'COM-C01', 'Tres cotizaciones y autorización por niveles; declaración anual de conflicto de interés', 'preventivo', 'manual', 'continua', true,
    { cuenta: 'Costo de ventas / Proveedores', aseveraciones: 'Existencia u ocurrencia' }),
  f('Cumplimiento Sanitario', 'Licencias y avisos', 'SAN-R01', 'Licencias, avisos o responsables sanitarios vencidos',
    'Operar con permisos vencidos expone a clausura por COFEPRIS.',
    'Cumplimiento con leyes', 2, 5, 'SAN-C01', 'Matriz de licencias y vencimientos con alertas a 90 días', 'preventivo', 'manual', 'mensual', true),
];

const CORPORATIVO = [
  f('Compras y Cuentas por Pagar', 'Proveedores', 'CXP-R01', 'Pagos a proveedores inexistentes o duplicados',
    'Alta de proveedores sin validación y pagos sin factura validada permiten desvíos.',
    'Fraude interno', 3, 4, 'CXP-C01', 'Alta de proveedores con validación de RFC, opinión de cumplimiento y lista 69-B del SAT', 'preventivo', 'manual', 'continua', true,
    { cuenta: 'Proveedores', aseveraciones: 'Existencia u ocurrencia' }),
  f('Compras y Cuentas por Pagar', 'Pagos', 'CXP-R02', 'Pagos sin recepción del bien o servicio (falta de cotejo a tres vías)',
    'Se pagan facturas sin orden de compra ni recepción.',
    'Proceso', 3, 4, 'CXP-C02', 'Cotejo a tres vías: orden de compra, recepción y factura antes de programar el pago', 'preventivo', 'automatico', 'continua', true),
  f('Ventas y Cuentas por Cobrar', 'Facturación', 'CXC-R01', 'Ingresos reconocidos en periodo incorrecto',
    'Facturación anticipada o tardía distorsiona resultados (corte de operaciones).',
    'Contable', 3, 4, 'CXC-C01', 'Revisión de corte de ventas al cierre: facturas de los últimos y primeros cinco días contra evidencia de entrega', 'detectivo', 'manual', 'mensual', true,
    { cuenta: 'Ingresos', aseveraciones: 'Corte, Existencia u ocurrencia' }),
  f('Ventas y Cuentas por Cobrar', 'Crédito y cobranza', 'CXC-R02', 'Cartera vencida sin estimación de incobrables',
    'Saldos antiguos no reservados sobrestiman activos.',
    'Contable', 3, 3, 'CXC-C02', 'Antigüedad de saldos mensual y estimación conforme a política aprobada', 'detectivo', 'manual', 'mensual', true,
    { cuenta: 'Clientes / Estimación de cuentas incobrables', aseveraciones: 'Valuación' }),
  f('Nómina y Capital Humano', 'Nómina', 'NOM-R01', 'Pagos de nómina a empleados inexistentes o dados de baja',
    'Altas y bajas no sincronizadas permiten pagos indebidos.',
    'Fraude interno', 2, 4, 'NOM-C01', 'Conciliación mensual de plantilla autorizada contra nómina pagada y movimientos IMSS', 'detectivo', 'manual', 'mensual', true,
    { cuenta: 'Gastos de personal', aseveraciones: 'Existencia u ocurrencia' }),
  f('Nómina y Capital Humano', 'Cumplimiento laboral', 'NOM-R02', 'Incumplimiento en obligaciones IMSS, INFONAVIT y REPSE',
    'Errores en cuotas o subcontratación indebida generan multas y créditos fiscales.',
    'Cumplimiento con leyes', 3, 4, 'NOM-C02', 'Revisión bimestral de determinación de cuotas y verificación de registro REPSE de proveedores de servicios', 'detectivo', 'manual', 'bimestral', false),
  f('Tesorería', 'Bancos', 'TES-R01', 'Disposiciones bancarias no autorizadas',
    'Firmas individuales o tokens compartidos permiten transferencias indebidas.',
    'Fraude interno', 3, 5, 'TES-C01', 'Esquema de firmas mancomunadas y límites de transferencia en banca electrónica', 'preventivo', 'automatico', 'continua', true,
    { cuenta: 'Bancos', aseveraciones: 'Existencia u ocurrencia' }),
  f('Contabilidad e Impuestos', 'Cierre contable', 'CON-R01', 'Pólizas manuales sin soporte ni autorización',
    'Ajustes manuales al cierre pueden ocultar errores o manipular resultados.',
    'Contable', 3, 4, 'CON-C01', 'Revisión y autorización de pólizas manuales de cierre por el Contralor con soporte documental', 'detectivo', 'manual', 'mensual', true,
    { aseveraciones: 'Exactitud, Presentación y revelación' }),
  f('Contabilidad e Impuestos', 'Impuestos', 'CON-R02', 'Determinación incorrecta de impuestos o deducciones no estrictamente indispensables',
    'Errores en cálculo o deducción de comprobantes no válidos generan contingencias fiscales.',
    'Impuestos', 3, 4, 'CON-C02', 'Papel de trabajo de impuestos revisado por asesor fiscal y validación de CFDI contra el SAT', 'detectivo', 'manual', 'mensual', true),
  f('Tecnología', 'Accesos', 'TI-R01', 'Accesos no autorizados al ERP',
    'Perfiles excesivos o cuentas de ex empleados activas permiten operaciones indebidas.',
    'Información y Ciberseguridad', 3, 4, 'TI-C01', 'Revisión trimestral de usuarios y segregación de funciones en el ERP', 'detectivo', 'manual', 'trimestral', true),
  f('Gobierno Corporativo', 'Órganos de gobierno', 'GOB-R01', 'Decisiones relevantes sin aprobación de los órganos de gobierno',
    'Operaciones con partes relacionadas o inversiones sin aprobación del Consejo.',
    'Gobierno', 2, 5, 'GOB-C01', 'Matriz de facultades y actas de Consejo con seguimiento de acuerdos', 'preventivo', 'manual', 'trimestral', true),
  f('Gobierno Corporativo', 'Ética', 'GOB-R02', 'Conductas contrarias al Código de Ética no detectadas',
    'Ausencia de canal de denuncia impide detectar fraudes y conflictos de interés.',
    'Gobierno', 3, 4, 'GOB-C02', 'Línea ética anónima con seguimiento del Comité de Ética e informe trimestral', 'detectivo', 'manual', 'trimestral', false),
];

export const PLANTILLAS = {
  sofom: { nombre: 'SOFOM / Servicios financieros', descripcion: 'Crédito, cobranza, PLD, tesorería, TI y cumplimiento CNBV/CONDUSEF', filas: SOFOM },
  hospital: { nombre: 'Hospital / Servicios de salud', descripcion: 'Admisión, facturación a aseguradoras, farmacia, quirófano, expediente clínico y COFEPRIS', filas: HOSPITAL },
  corporativo: { nombre: 'Empresa corporativa (general)', descripcion: 'Compras, ventas, nómina, tesorería, contabilidad, impuestos, TI y gobierno', filas: CORPORATIVO },
};
